/**
 * WARNING: This file is auto-generated and should in no case be tempered with.
 * It only contains the player infractions database, generated by a bot based on a .json file, into Squirrel code.
 * Proceed at your own risk.
 */

global table<string, array<PlayerInfraction>> Spyglass_Infractions =
{
    ["1008806725370"] =
    [
        { PlayerUsername = "Neinguar", Type = InfractionType.ChatSpam, Date = "01/01/1970 00:00:00" , Issuer = "NoCatt#8128", Reason = "Too cool" }
    ]
}