/**
 * WARNING: This file is auto-generated and should in no case be tempered with.
 * It only contains the player infractions database, generated by a bot based on a .json file, into Squirrel code.
 * Proceed at your own risk.
 */

global function Spyglass_Database_Init;
global table<string, array<Spyglass_PlayerInfraction> > Spyglass_Infractions = {}
global table<string, string> Spyglass_PlayerNameUIDMap = {}

void function Spyglass_Database_Init()
{
    printt("==========================================");
    printt("[Spyglass] Loading autogenerated database.");
    printt("==========================================");

    array<Spyglass_PlayerInfraction> infractions = [];
    Spyglass_PlayerInfraction currentInfraction;

    // 1005782992766
    infractions = [];
    currentInfraction.ID = 122;
	currentInfraction.PlayerUsername = "lonelykilla23";
	currentInfraction.Type = Spyglass_InfractionType.Cheating;
	currentInfraction.Date = "02-FEB-22";
	currentInfraction.Reason = "Aimbot.";
	
    infractions.append(clone currentInfraction);
    currentInfraction.ID = 1;
	currentInfraction.PlayerUsername = "lonelykilla23";
	currentInfraction.Type = Spyglass_InfractionType.Cheating;
	currentInfraction.Date = "18-SEPT-22";
	currentInfraction.Reason = "Wallhacks and aimbot.";
	
    infractions.append(clone currentInfraction);
    currentInfraction.ID = 2;
	currentInfraction.PlayerUsername = "lonelykilla23";
	currentInfraction.Type = Spyglass_InfractionType.Cheating;
	currentInfraction.Date = "18-SEPT-22";
	currentInfraction.Reason = "Aimbot, wallhacks.";
	
    infractions.append(clone currentInfraction);
    currentInfraction.ID = 58;
	currentInfraction.PlayerUsername = "lonelykilla23";
	currentInfraction.Type = Spyglass_InfractionType.Cheating;
	currentInfraction.Date = "18-SEPT-22";
	currentInfraction.Reason = "Aimbot & wallhacks.";
	
    infractions.append(clone currentInfraction);
    Spyglass_Infractions["1005782992766"] <- clone infractions;

    // 1003520719357
    infractions = [];
    currentInfraction.ID = 3;
	currentInfraction.PlayerUsername = "P4TR1X_G";
	currentInfraction.Type = Spyglass_InfractionType.Discrimination;
	currentInfraction.Date = "17-SEPT-22";
	currentInfraction.Reason = "Racist slurs in chat.";
	
    infractions.append(clone currentInfraction);
    Spyglass_Infractions["1003520719357"] <- clone infractions;

    // 1008622084773
    infractions = [];
    currentInfraction.ID = 4;
	currentInfraction.PlayerUsername = "quadrupeldamag";
	currentInfraction.Type = Spyglass_InfractionType.Cheating;
	currentInfraction.Date = "18-SEPT-22";
	currentInfraction.Reason = "Aimbot and wallhacks.";
	
    infractions.append(clone currentInfraction);
    Spyglass_Infractions["1008622084773"] <- clone infractions;

    // 1011452735139
    infractions = [];
    currentInfraction.ID = 5;
	currentInfraction.PlayerUsername = "IamDavidoff2k2";
	currentInfraction.Type = Spyglass_InfractionType.Discrimination;
	currentInfraction.Date = "14-SEPT-22";
	currentInfraction.Reason = "Homophobia in text chat.";
	
    infractions.append(clone currentInfraction);
    Spyglass_Infractions["1011452735139"] <- clone infractions;

    // 2655753508
    infractions = [];
    currentInfraction.ID = 88;
	currentInfraction.PlayerUsername = "JesusMango";
	currentInfraction.Type = Spyglass_InfractionType.Discrimination;
	currentInfraction.Date = "03-MAY-22";
	currentInfraction.Reason = "Racial slur in chat.";
	
    infractions.append(clone currentInfraction);
    currentInfraction.ID = 87;
	currentInfraction.PlayerUsername = "JesusMango";
	currentInfraction.Type = Spyglass_InfractionType.Discrimination;
	currentInfraction.Date = "03-MAY-22";
	currentInfraction.Reason = "Racial slur in chat.";
	
    infractions.append(clone currentInfraction);
    currentInfraction.ID = 84;
	currentInfraction.PlayerUsername = "JesusMango";
	currentInfraction.Type = Spyglass_InfractionType.Discrimination;
	currentInfraction.Date = "05-MAY-22";
	currentInfraction.Reason = "Racial slur in chat.";
	
    infractions.append(clone currentInfraction);
    currentInfraction.ID = 82;
	currentInfraction.PlayerUsername = "JesusMango";
	currentInfraction.Type = Spyglass_InfractionType.Discrimination;
	currentInfraction.Date = "08-MAY-22";
	currentInfraction.Reason = "Racial slurs in chat.";
	
    infractions.append(clone currentInfraction);
    currentInfraction.ID = 41;
	currentInfraction.PlayerUsername = "JesusMango";
	currentInfraction.Type = Spyglass_InfractionType.Discrimination;
	currentInfraction.Date = "05-JUL-22";
	currentInfraction.Reason = "Racial slurs in chat.";
	
    infractions.append(clone currentInfraction);
    currentInfraction.ID = 27;
	currentInfraction.PlayerUsername = "JesusMango";
	currentInfraction.Type = Spyglass_InfractionType.Discrimination;
	currentInfraction.Date = "24-JUL-22";
	currentInfraction.Reason = "Antisemitism.";
	
    infractions.append(clone currentInfraction);
    currentInfraction.ID = 21;
	currentInfraction.PlayerUsername = "JesusMango";
	currentInfraction.Type = Spyglass_InfractionType.Discrimination;
	currentInfraction.Date = "04-AUG-22";
	currentInfraction.Reason = "Use of racial slurs.";
	
    infractions.append(clone currentInfraction);
    currentInfraction.ID = 20;
	currentInfraction.PlayerUsername = "JesusMango";
	currentInfraction.Type = Spyglass_InfractionType.Discrimination;
	currentInfraction.Date = "05-AUG-22";
	currentInfraction.Reason = "Racial slurs in chat.";
	
    infractions.append(clone currentInfraction);
    currentInfraction.ID = 17;
	currentInfraction.PlayerUsername = "JesusMango";
	currentInfraction.Type = Spyglass_InfractionType.Discrimination;
	currentInfraction.Date = "09-AUG-22";
	currentInfraction.Reason = "Spamming racial slurs.";
	
    infractions.append(clone currentInfraction);
    currentInfraction.ID = 12;
	currentInfraction.PlayerUsername = "JesusMango";
	currentInfraction.Type = Spyglass_InfractionType.Discrimination;
	currentInfraction.Date = "14-AUG-22";
	currentInfraction.Reason = "Spamming of racial slurs.";
	
    infractions.append(clone currentInfraction);
    currentInfraction.ID = 6;
	currentInfraction.PlayerUsername = "JesusMango";
	currentInfraction.Type = Spyglass_InfractionType.Discrimination;
	currentInfraction.Date = "14-SEPT-22";
	currentInfraction.Reason = "Spamming racial slurs.";
	
    infractions.append(clone currentInfraction);
    Spyglass_Infractions["2655753508"] <- clone infractions;

    // 1012893329720
    infractions = [];
    currentInfraction.ID = 7;
	currentInfraction.PlayerUsername = "MedicalMeccanica";
	currentInfraction.Type = Spyglass_InfractionType.Cheating;
	currentInfraction.Date = "10-SEPT-22";
	currentInfraction.Reason = "Speedhacks and aimbot.";
	
    infractions.append(clone currentInfraction);
    Spyglass_Infractions["1012893329720"] <- clone infractions;

    // 1006249545593
    infractions = [];
    currentInfraction.ID = 8;
	currentInfraction.PlayerUsername = "kubatdc";
	currentInfraction.Type = Spyglass_InfractionType.Cheating;
	currentInfraction.Date = "05-SEPT-22";
	currentInfraction.Reason = "Aimbotting.";
	
    infractions.append(clone currentInfraction);
    Spyglass_Infractions["1006249545593"] <- clone infractions;

    // 1013244775476
    infractions = [];
    currentInfraction.ID = 9;
	currentInfraction.PlayerUsername = "wagwanbigmanS";
	currentInfraction.Type = Spyglass_InfractionType.Cheating;
	currentInfraction.Date = "27-AUG-22";
	currentInfraction.Reason = "Aimbot.";
	
    infractions.append(clone currentInfraction);
    Spyglass_Infractions["1013244775476"] <- clone infractions;

    // 1011345449670
    infractions = [];
    currentInfraction.ID = 29;
	currentInfraction.PlayerUsername = "MrFogg";
	currentInfraction.Type = Spyglass_InfractionType.Discrimination;
	currentInfraction.Date = "19-JUL-22";
	currentInfraction.Reason = "Homophobic slurs.";
	
    infractions.append(clone currentInfraction);
    currentInfraction.ID = 10;
	currentInfraction.PlayerUsername = "MrFogg";
	currentInfraction.Type = Spyglass_InfractionType.Discrimination;
	currentInfraction.Date = "17-AUG-22";
	currentInfraction.Reason = "Spamming homophobia in text chat.";
	
    infractions.append(clone currentInfraction);
    Spyglass_Infractions["1011345449670"] <- clone infractions;

    // 1011457670714
    infractions = [];
    currentInfraction.ID = 11;
	currentInfraction.PlayerUsername = "ConcernedPencil0";
	currentInfraction.Type = Spyglass_InfractionType.Cheating;
	currentInfraction.Date = "22-AUG-22";
	currentInfraction.Reason = "Aimbot and wallhacks.";
	
    infractions.append(clone currentInfraction);
    Spyglass_Infractions["1011457670714"] <- clone infractions;

    // 1007544128057
    infractions = [];
    currentInfraction.ID = 13;
	currentInfraction.PlayerUsername = "woahdev";
	currentInfraction.Type = Spyglass_InfractionType.Cheating;
	currentInfraction.Date = "25-AUG-22";
	currentInfraction.Reason = "Aimbotting and wallhacks.";
	
    infractions.append(clone currentInfraction);
    Spyglass_Infractions["1007544128057"] <- clone infractions;

    // 1007319692607
    infractions = [];
    currentInfraction.ID = 14;
	currentInfraction.PlayerUsername = "Killer69Y";
	currentInfraction.Type = Spyglass_InfractionType.Cheating;
	currentInfraction.Date = "14-AUG-22";
	currentInfraction.Reason = "Aimbot and wallhacks.";
	
    infractions.append(clone currentInfraction);
    Spyglass_Infractions["1007319692607"] <- clone infractions;

    // 1000180140014
    infractions = [];
    currentInfraction.ID = 15;
	currentInfraction.PlayerUsername = "XsnipezX21";
	currentInfraction.Type = Spyglass_InfractionType.Discrimination;
	currentInfraction.Date = "14-AUG-22";
	currentInfraction.Reason = "Spamming of racial slurs.";
	
    infractions.append(clone currentInfraction);
    Spyglass_Infractions["1000180140014"] <- clone infractions;

    // 1010161190670
    infractions = [];
    currentInfraction.ID = 16;
	currentInfraction.PlayerUsername = "SenpaiVT";
	currentInfraction.Type = Spyglass_InfractionType.Cheating;
	currentInfraction.Date = "09-AUG-22";
	currentInfraction.Reason = "Speedhacks and aimbot.";
	
    infractions.append(clone currentInfraction);
    Spyglass_Infractions["1010161190670"] <- clone infractions;

    // 1008988079827
    infractions = [];
    currentInfraction.ID = 18;
	currentInfraction.PlayerUsername = "ISnipSnipSnip";
	currentInfraction.Type = Spyglass_InfractionType.Discrimination;
	currentInfraction.Date = "06-AUG-22";
	currentInfraction.Reason = "Racial slur in chat.";
	
    infractions.append(clone currentInfraction);
    Spyglass_Infractions["1008988079827"] <- clone infractions;

    // 1008122720592
    infractions = [];
    currentInfraction.ID = 19;
	currentInfraction.PlayerUsername = "UwUHun3ter";
	currentInfraction.Type = Spyglass_InfractionType.Cheating;
	currentInfraction.Date = "07-AUG-22";
	currentInfraction.Reason = "Wallhacking.";
	
    infractions.append(clone currentInfraction);
    Spyglass_Infractions["1008122720592"] <- clone infractions;

    // 1012632396446
    infractions = [];
    currentInfraction.ID = 22;
	currentInfraction.PlayerUsername = "BattleritePump";
	currentInfraction.Type = Spyglass_InfractionType.Discrimination;
	currentInfraction.Date = "05-AUG-22";
	currentInfraction.Reason = "Transphobic messages in text chat.";
	
    infractions.append(clone currentInfraction);
    Spyglass_Infractions["1012632396446"] <- clone infractions;

    // 1000092519211
    infractions = [];
    currentInfraction.ID = 23;
	currentInfraction.PlayerUsername = "ghostxvii";
	currentInfraction.Type = Spyglass_InfractionType.Discrimination;
	currentInfraction.Date = "01-AUG-22";
	currentInfraction.Reason = "Antisemitic slurs in text chat.";
	
    infractions.append(clone currentInfraction);
    Spyglass_Infractions["1000092519211"] <- clone infractions;

    // 1008973146907
    infractions = [];
    currentInfraction.ID = 24;
	currentInfraction.PlayerUsername = "Phantom_Raimando";
	currentInfraction.Type = Spyglass_InfractionType.Cheating;
	currentInfraction.Date = "02-AUG-22";
	currentInfraction.Reason = "Aimbot.";
	
    infractions.append(clone currentInfraction);
    Spyglass_Infractions["1008973146907"] <- clone infractions;

    // 1011795366781
    infractions = [];
    currentInfraction.ID = 25;
	currentInfraction.PlayerUsername = "coconuts_004";
	currentInfraction.Type = Spyglass_InfractionType.Discrimination;
	currentInfraction.Date = "31-JUL-22";
	currentInfraction.Reason = "Use of racial slurs.";
	
    infractions.append(clone currentInfraction);
    Spyglass_Infractions["1011795366781"] <- clone infractions;

    // 1011134487508
    infractions = [];
    currentInfraction.ID = 114;
	currentInfraction.PlayerUsername = "m0rbidc0rvid";
	currentInfraction.Type = Spyglass_InfractionType.Discrimination;
	currentInfraction.Date = "02-MAR-22";
	currentInfraction.Reason = "Homophobic slurs in chat.";
	
    infractions.append(clone currentInfraction);
    currentInfraction.ID = 26;
	currentInfraction.PlayerUsername = "m0rbidc0rvid";
	currentInfraction.Type = Spyglass_InfractionType.Discrimination;
	currentInfraction.Date = "26-JUL-22";
	currentInfraction.Reason = "Use of homophobic slurs.";
	
    infractions.append(clone currentInfraction);
    Spyglass_Infractions["1011134487508"] <- clone infractions;

    // 1000186323332
    infractions = [];
    currentInfraction.ID = 28;
	currentInfraction.PlayerUsername = "G0Fesh";
	currentInfraction.Type = Spyglass_InfractionType.Discrimination;
	currentInfraction.Date = "22-JUL-22";
	currentInfraction.Reason = "Spamming racial slurs.";
	
    infractions.append(clone currentInfraction);
    Spyglass_Infractions["1000186323332"] <- clone infractions;

    // 1011897054369
    infractions = [];
    currentInfraction.ID = 104;
	currentInfraction.PlayerUsername = "cheesegratermanx";
	currentInfraction.Type = Spyglass_InfractionType.Discrimination;
	currentInfraction.Date = "01-APR-22";
	currentInfraction.Reason = "Racial slur in chat.";
	
    infractions.append(clone currentInfraction);
    currentInfraction.ID = 30;
	currentInfraction.PlayerUsername = "awesomeguy41";
	currentInfraction.Type = Spyglass_InfractionType.Spoof;
	currentInfraction.Date = "20-JUL-22";
	currentInfraction.Reason = "(Spoofed) Wallhacks and aimbot.";
	
    infractions.append(clone currentInfraction);
    Spyglass_Infractions["1011897054369"] <- clone infractions;

    // 1009821473677
    infractions = [];
    currentInfraction.ID = 31;
	currentInfraction.PlayerUsername = "FuzzqMinotaur97";
	currentInfraction.Type = Spyglass_InfractionType.Spoof;
	currentInfraction.Date = "10-JUL-22";
	currentInfraction.Reason = "(Spoofed) Aimbot and wallhacks.";
	
    infractions.append(clone currentInfraction);
    Spyglass_Infractions["1009821473677"] <- clone infractions;

    // 1011116972357
    infractions = [];
    currentInfraction.ID = 32;
	currentInfraction.PlayerUsername = "TaMagicznaFlet";
	currentInfraction.Type = Spyglass_InfractionType.Discrimination;
	currentInfraction.Date = "10-JUL-22";
	currentInfraction.Reason = "Racial slurs in chat.";
	
    infractions.append(clone currentInfraction);
    Spyglass_Infractions["1011116972357"] <- clone infractions;

    // 2251932307
    infractions = [];
    currentInfraction.ID = 33;
	currentInfraction.PlayerUsername = "ogtsilva";
	currentInfraction.Type = Spyglass_InfractionType.Cheating;
	currentInfraction.Date = "09-JUL-22";
	currentInfraction.Reason = "Aimbot and speehacks.";
	
    infractions.append(clone currentInfraction);
    Spyglass_Infractions["2251932307"] <- clone infractions;

    // 1006063431799
    infractions = [];
    currentInfraction.ID = 34;
	currentInfraction.PlayerUsername = "RogueBananaBTW";
	currentInfraction.Type = Spyglass_InfractionType.Spoof;
	currentInfraction.Date = "07-JUL-22";
	currentInfraction.Reason = "Server crash and speedhacks.";
	
    infractions.append(clone currentInfraction);
    Spyglass_Infractions["1006063431799"] <- clone infractions;

    // 2250141414
    infractions = [];
    currentInfraction.ID = 44;
	currentInfraction.PlayerUsername = "FloridaBiker";
	currentInfraction.Type = Spyglass_InfractionType.Discrimination;
	currentInfraction.Date = "27-JUN-22";
	currentInfraction.Reason = "Homophobic slur in voice chat.";
	
    infractions.append(clone currentInfraction);
    currentInfraction.ID = 38;
	currentInfraction.PlayerUsername = "FloridaBiker";
	currentInfraction.Type = Spyglass_InfractionType.Discrimination;
	currentInfraction.Date = "08-JUL-22";
	currentInfraction.Reason = "Homophobic slurs and threatening violence.";
	
    infractions.append(clone currentInfraction);
    currentInfraction.ID = 35;
	currentInfraction.PlayerUsername = "FloridaBiker";
	currentInfraction.Type = Spyglass_InfractionType.Discrimination;
	currentInfraction.Date = "28-JUL-22";
	currentInfraction.Reason = "Homophobic slurs";
	
    infractions.append(clone currentInfraction);
    currentInfraction.ID = 36;
	currentInfraction.PlayerUsername = "FloridaBiker";
	currentInfraction.Type = Spyglass_InfractionType.Discrimination;
	currentInfraction.Date = "28-JUL-22";
	currentInfraction.Reason = "Homophobic slurs";
	
    infractions.append(clone currentInfraction);
    Spyglass_Infractions["2250141414"] <- clone infractions;

    // 1009805930043
    infractions = [];
    currentInfraction.ID = 37;
	currentInfraction.PlayerUsername = "Stefanthegrate16";
	currentInfraction.Type = Spyglass_InfractionType.Discrimination;
	currentInfraction.Date = "06-JUL-22";
	currentInfraction.Reason = "Use of racial slurs.";
	
    infractions.append(clone currentInfraction);
    currentInfraction.ID = 39;
	currentInfraction.PlayerUsername = "Stefanthegrate16";
	currentInfraction.Type = Spyglass_InfractionType.Discrimination;
	currentInfraction.Date = "31-JUL-22";
	currentInfraction.Reason = "Use of racial slurs.";
	
    infractions.append(clone currentInfraction);
    Spyglass_Infractions["1009805930043"] <- clone infractions;

    // 1008231879388
    infractions = [];
    currentInfraction.ID = 40;
	currentInfraction.PlayerUsername = "Sumboro";
	currentInfraction.Type = Spyglass_InfractionType.Cheating;
	currentInfraction.Date = "06-JUL-22";
	currentInfraction.Reason = "Speedhacking, infinite flight.";
	
    infractions.append(clone currentInfraction);
    Spyglass_Infractions["1008231879388"] <- clone infractions;

    // 1009767928840
    infractions = [];
    currentInfraction.ID = 42;
	currentInfraction.PlayerUsername = "Trouble439";
	currentInfraction.Type = Spyglass_InfractionType.Discrimination;
	currentInfraction.Date = "05-JUL-22";
	currentInfraction.Reason = "Racial slurs in chat.";
	
    infractions.append(clone currentInfraction);
    Spyglass_Infractions["1009767928840"] <- clone infractions;

    // 1004184060749
    infractions = [];
    currentInfraction.ID = 43;
	currentInfraction.PlayerUsername = "Mr_NotSuspicious";
	currentInfraction.Type = Spyglass_InfractionType.Cheating;
	currentInfraction.Date = "01-JUL-22";
	currentInfraction.Reason = "Aimbot and wallhacks.";
	
    infractions.append(clone currentInfraction);
    Spyglass_Infractions["1004184060749"] <- clone infractions;

    // 1008593965434
    infractions = [];
    currentInfraction.ID = 45;
	currentInfraction.PlayerUsername = "Submensch";
	currentInfraction.Type = Spyglass_InfractionType.Discrimination;
	currentInfraction.Date = "26-JUN-22";
	currentInfraction.Reason = "Use of racial slurs.";
	
    infractions.append(clone currentInfraction);
    Spyglass_Infractions["1008593965434"] <- clone infractions;

    // 1013391767921
    infractions = [];
    currentInfraction.ID = 47;
	currentInfraction.PlayerUsername = "HextechMan";
	currentInfraction.Type = Spyglass_InfractionType.Cheating;
	currentInfraction.Date = "23-JUN-22";
	currentInfraction.Reason = "Aimbot and wallhacks.";
	
    infractions.append(clone currentInfraction);
    currentInfraction.ID = 48;
	currentInfraction.PlayerUsername = "HextechMan";
	currentInfraction.Type = Spyglass_InfractionType.Cheating;
	currentInfraction.Date = "23-JUN-22";
	currentInfraction.Reason = "Aimbot and wallhacks.";
	
    infractions.append(clone currentInfraction);
    currentInfraction.ID = 46;
	currentInfraction.PlayerUsername = "HextechMan";
	currentInfraction.Type = Spyglass_InfractionType.Cheating;
	currentInfraction.Date = "26-JUN-22";
	currentInfraction.Reason = "Aimbot and wallhacks.";
	
    infractions.append(clone currentInfraction);
    Spyglass_Infractions["1013391767921"] <- clone infractions;

    // 1008873731189
    infractions = [];
    currentInfraction.ID = 49;
	currentInfraction.PlayerUsername = "Cosmos-Da-Cat";
	currentInfraction.Type = Spyglass_InfractionType.Discrimination;
	currentInfraction.Date = "22-JUN-22";
	currentInfraction.Reason = "Spamming homophobic slurs.";
	
    infractions.append(clone currentInfraction);
    Spyglass_Infractions["1008873731189"] <- clone infractions;

    // 2321091843
    infractions = [];
    currentInfraction.ID = 50;
	currentInfraction.PlayerUsername = "TheWarflash";
	currentInfraction.Type = Spyglass_InfractionType.Cheating;
	currentInfraction.Date = "22-JUN-22";
	currentInfraction.Reason = "Aimbot.";
	
    infractions.append(clone currentInfraction);
    Spyglass_Infractions["2321091843"] <- clone infractions;

    // 1009690917669
    infractions = [];
    currentInfraction.ID = 92;
	currentInfraction.PlayerUsername = "Thavage_Soul";
	currentInfraction.Type = Spyglass_InfractionType.Cheating;
	currentInfraction.Date = "01-MAY-22";
	currentInfraction.Reason = "Aimbot.";
	
    infractions.append(clone currentInfraction);
    currentInfraction.ID = 51;
	currentInfraction.PlayerUsername = "Thavage_Soul";
	currentInfraction.Type = Spyglass_InfractionType.Cheating;
	currentInfraction.Date = "21-JUN-22";
	currentInfraction.Reason = "Aimbot & no recoil.";
	
    infractions.append(clone currentInfraction);
    Spyglass_Infractions["1009690917669"] <- clone infractions;

    // 1000349712299
    infractions = [];
    currentInfraction.ID = 52;
	currentInfraction.PlayerUsername = "yourtrashkid1215";
	currentInfraction.Type = Spyglass_InfractionType.Cheating;
	currentInfraction.Date = "21-JUN-22";
	currentInfraction.Reason = "Aimbot.";
	
    infractions.append(clone currentInfraction);
    Spyglass_Infractions["1000349712299"] <- clone infractions;

    // 1007299698120
    infractions = [];
    currentInfraction.ID = 56;
	currentInfraction.PlayerUsername = "SammieDonk";
	currentInfraction.Type = Spyglass_InfractionType.Cheating;
	currentInfraction.Date = "16-JUN-22";
	currentInfraction.Reason = "Aimbot and wallhacks.";
	
    infractions.append(clone currentInfraction);
    currentInfraction.ID = 53;
	currentInfraction.PlayerUsername = "SammieDonk";
	currentInfraction.Type = Spyglass_InfractionType.Cheating;
	currentInfraction.Date = "20-JUN-22";
	currentInfraction.Reason = "Aimbot.";
	
    infractions.append(clone currentInfraction);
    Spyglass_Infractions["1007299698120"] <- clone infractions;

    // 1010773614705
    infractions = [];
    currentInfraction.ID = 54;
	currentInfraction.PlayerUsername = "NickLink217";
	currentInfraction.Type = Spyglass_InfractionType.Cheating;
	currentInfraction.Date = "20-JUN-22";
	currentInfraction.Reason = "Aimbot & speedhacks.";
	
    infractions.append(clone currentInfraction);
    Spyglass_Infractions["1010773614705"] <- clone infractions;

    // 1009589129089
    infractions = [];
    currentInfraction.ID = 55;
	currentInfraction.PlayerUsername = "SuperBlyatman101";
	currentInfraction.Type = Spyglass_InfractionType.Cheating;
	currentInfraction.Date = "20-JUN-22";
	currentInfraction.Reason = "Aimbot & speedhacks.";
	
    infractions.append(clone currentInfraction);
    Spyglass_Infractions["1009589129089"] <- clone infractions;

    // 1009417714028
    infractions = [];
    currentInfraction.ID = 61;
	currentInfraction.PlayerUsername = "xXh1gHrOlLeRxX";
	currentInfraction.Type = Spyglass_InfractionType.Cheating;
	currentInfraction.Date = "10-JUN-22";
	currentInfraction.Reason = "Aimbot & wallhacks.";
	
    infractions.append(clone currentInfraction);
    currentInfraction.ID = 59;
	currentInfraction.PlayerUsername = "xXh1gHrOlLeRxX";
	currentInfraction.Type = Spyglass_InfractionType.Discrimination;
	currentInfraction.Date = "10-JUN-22";
	currentInfraction.Reason = "Spamming racial slurs in chat.";
	
    infractions.append(clone currentInfraction);
    currentInfraction.ID = 60;
	currentInfraction.PlayerUsername = "xXh1gHrOlLeRxX";
	currentInfraction.Type = Spyglass_InfractionType.Discrimination;
	currentInfraction.Date = "10-JUN-22";
	currentInfraction.Reason = "Spamming racial slurs in chat, again.";
	
    infractions.append(clone currentInfraction);
    Spyglass_Infractions["1009417714028"] <- clone infractions;

    // 1006636445131
    infractions = [];
    currentInfraction.ID = 62;
	currentInfraction.PlayerUsername = "TheRealEpicFlame";
	currentInfraction.Type = Spyglass_InfractionType.Toxicity;
	currentInfraction.Date = "08-JUN-22";
	currentInfraction.Reason = "Rape threats.";
	
    infractions.append(clone currentInfraction);
    Spyglass_Infractions["1006636445131"] <- clone infractions;

    // 1007313236586
    infractions = [];
    currentInfraction.ID = 64;
	currentInfraction.PlayerUsername = "eyeballmuncher47";
	currentInfraction.Type = Spyglass_InfractionType.Spamming;
	currentInfraction.Date = "31-MAY-22";
	currentInfraction.Reason = "Spamming chat continuously.";
	
    infractions.append(clone currentInfraction);
    currentInfraction.ID = 63;
	currentInfraction.PlayerUsername = "definitionofcool";
	currentInfraction.Type = Spyglass_InfractionType.Cheating;
	currentInfraction.Date = "05-JUN-22";
	currentInfraction.Reason = "Chat spam, wallhacks, exploits.";
	
    infractions.append(clone currentInfraction);
    Spyglass_Infractions["1007313236586"] <- clone infractions;

    // 1011158646016
    infractions = [];
    currentInfraction.ID = 65;
	currentInfraction.PlayerUsername = "ChargeHack";
	currentInfraction.Type = Spyglass_InfractionType.Cheating;
	currentInfraction.Date = "01-JUN-22";
	currentInfraction.Reason = "Aimbot and wallhacks.";
	
    infractions.append(clone currentInfraction);
    Spyglass_Infractions["1011158646016"] <- clone infractions;

    // 2311733905
    infractions = [];
    currentInfraction.ID = 67;
	currentInfraction.PlayerUsername = "fdac3c83ccbd903fa5c1499a6f6cad24";
	currentInfraction.Type = Spyglass_InfractionType.Cheating;
	currentInfraction.Date = "28-MAY-22";
	currentInfraction.Reason = "Speed hacks and aimbot.";
	
    infractions.append(clone currentInfraction);
    currentInfraction.ID = 66;
	currentInfraction.PlayerUsername = "fdac3c83ccbd903fa5c1499a6f6cad24";
	currentInfraction.Type = Spyglass_InfractionType.Cheating;
	currentInfraction.Date = "28-MAY-22";
	currentInfraction.Reason = "Out of bounds exploit & server crash.";
	
    infractions.append(clone currentInfraction);
    Spyglass_Infractions["2311733905"] <- clone infractions;

    // 1011604298047
    infractions = [];
    currentInfraction.ID = 68;
	currentInfraction.PlayerUsername = "cabober";
	currentInfraction.Type = Spyglass_InfractionType.Cheating;
	currentInfraction.Date = "25-MAY-22";
	currentInfraction.Reason = "Aimbot and infinite abilities.";
	
    infractions.append(clone currentInfraction);
    Spyglass_Infractions["1011604298047"] <- clone infractions;

    // 1009796277318
    infractions = [];
    currentInfraction.ID = 69;
	currentInfraction.PlayerUsername = "Newew";
	currentInfraction.Type = Spyglass_InfractionType.Cheating;
	currentInfraction.Date = "23-MAY-22";
	currentInfraction.Reason = "Aimbot.";
	
    infractions.append(clone currentInfraction);
    Spyglass_Infractions["1009796277318"] <- clone infractions;

    // 1009685493971
    infractions = [];
    currentInfraction.ID = 70;
	currentInfraction.PlayerUsername = "shadow443";
	currentInfraction.Type = Spyglass_InfractionType.Cheating;
	currentInfraction.Date = "23-MAY-22";
	currentInfraction.Reason = "Aimbot and wallhacks.";
	
    infractions.append(clone currentInfraction);
    Spyglass_Infractions["1009685493971"] <- clone infractions;

    // 1008227051828
    infractions = [];
    currentInfraction.ID = 71;
	currentInfraction.PlayerUsername = "SupaL33THacker";
	currentInfraction.Type = Spyglass_InfractionType.Cheating;
	currentInfraction.Date = "19-MAY-22";
	currentInfraction.Reason = "Aimbot.";
	
    infractions.append(clone currentInfraction);
    Spyglass_Infractions["1008227051828"] <- clone infractions;

    // 1007901881439
    infractions = [];
    currentInfraction.ID = 72;
	currentInfraction.PlayerUsername = "Exact_Value";
	currentInfraction.Type = Spyglass_InfractionType.Discrimination;
	currentInfraction.Date = "18-MAY-22";
	currentInfraction.Reason = "Racial slur in chat.";
	
    infractions.append(clone currentInfraction);
    Spyglass_Infractions["1007901881439"] <- clone infractions;

    // 1006358680073
    infractions = [];
    currentInfraction.ID = 73;
	currentInfraction.PlayerUsername = "ThatFella_27_";
	currentInfraction.Type = Spyglass_InfractionType.Discrimination;
	currentInfraction.Date = "20-JUN-22";
	currentInfraction.Reason = "Racial slur in chat.";
	
    infractions.append(clone currentInfraction);
    Spyglass_Infractions["1006358680073"] <- clone infractions;

    // 1010517024687
    infractions = [];
    currentInfraction.ID = 74;
	currentInfraction.PlayerUsername = "Dester441";
	currentInfraction.Type = Spyglass_InfractionType.Cheating;
	currentInfraction.Date = "16-MAY-22";
	currentInfraction.Reason = "Aimbot & expoits.";
	
    infractions.append(clone currentInfraction);
    Spyglass_Infractions["1010517024687"] <- clone infractions;

    // 1012276100023
    infractions = [];
    currentInfraction.ID = 75;
	currentInfraction.PlayerUsername = "Moxi76";
	currentInfraction.Type = Spyglass_InfractionType.Toxicity;
	currentInfraction.Date = "02-SEPT-22";
	currentInfraction.Reason = "Telling other players to commit suicide.";
	
    infractions.append(clone currentInfraction);
    Spyglass_Infractions["1012276100023"] <- clone infractions;

    // 1008904554095
    infractions = [];
    currentInfraction.ID = 76;
	currentInfraction.PlayerUsername = "WatzKrakenn";
	currentInfraction.Type = Spyglass_InfractionType.Discrimination;
	currentInfraction.Date = "02-SEPT-22";
	currentInfraction.Reason = "Homophobic slurs in chat.";
	
    infractions.append(clone currentInfraction);
    Spyglass_Infractions["1008904554095"] <- clone infractions;

    // 1013163567703
    infractions = [];
    currentInfraction.ID = 77;
	currentInfraction.PlayerUsername = "ohmangoh";
	currentInfraction.Type = Spyglass_InfractionType.Cheating;
	currentInfraction.Date = "26-AUG-22";
	currentInfraction.Reason = "Aimbot and speedhacks.";
	
    infractions.append(clone currentInfraction);
    Spyglass_Infractions["1013163567703"] <- clone infractions;

    // 1011777372037
    infractions = [];
    currentInfraction.ID = 81;
	currentInfraction.PlayerUsername = "xiRunZxBoxLive_";
	currentInfraction.Type = Spyglass_InfractionType.Discrimination;
	currentInfraction.Date = "09-MAY-22";
	currentInfraction.Reason = "Racial slur in chat (and spamming).";
	
    infractions.append(clone currentInfraction);
    currentInfraction.ID = 80;
	currentInfraction.PlayerUsername = "xiRunZxBoxLive_";
	currentInfraction.Type = Spyglass_InfractionType.Cheating;
	currentInfraction.Date = "09-MAY-22";
	currentInfraction.Reason = "Aimbot and wallhacks.";
	
    infractions.append(clone currentInfraction);
    currentInfraction.ID = 79;
	currentInfraction.PlayerUsername = "whotfiswanderer";
	currentInfraction.Type = Spyglass_InfractionType.Spamming;
	currentInfraction.Date = "09-MAY-22";
	currentInfraction.Reason = "Spamming chat.";
	
    infractions.append(clone currentInfraction);
    currentInfraction.ID = 78;
	currentInfraction.PlayerUsername = "xiRunZxBoxLive_";
	currentInfraction.Type = Spyglass_InfractionType.Spamming;
	currentInfraction.Date = "09-MAY-22";
	currentInfraction.Reason = "Spamming chat.";
	
    infractions.append(clone currentInfraction);
    Spyglass_Infractions["1011777372037"] <- clone infractions;

    // 2342589311
    infractions = [];
    currentInfraction.ID = 94;
	currentInfraction.PlayerUsername = "evilsparky420";
	currentInfraction.Type = Spyglass_InfractionType.Discrimination;
	currentInfraction.Date = "23-APR-22";
	currentInfraction.Reason = "Racial and homophobic slurs in chat.";
	
    infractions.append(clone currentInfraction);
    currentInfraction.ID = 83;
	currentInfraction.PlayerUsername = "evilsparky420";
	currentInfraction.Type = Spyglass_InfractionType.Discrimination;
	currentInfraction.Date = "07-MAY-22";
	currentInfraction.Reason = "Racial slur in chat.";
	
    infractions.append(clone currentInfraction);
    Spyglass_Infractions["2342589311"] <- clone infractions;

    // 1012599329074
    infractions = [];
    currentInfraction.ID = 85;
	currentInfraction.PlayerUsername = "peigengchen";
	currentInfraction.Type = Spyglass_InfractionType.Cheating;
	currentInfraction.Date = "05-MAY-22";
	currentInfraction.Reason = "Aimbot.";
	
    infractions.append(clone currentInfraction);
    Spyglass_Infractions["1012599329074"] <- clone infractions;

    // 1003374325454
    infractions = [];
    currentInfraction.ID = 86;
	currentInfraction.PlayerUsername = "kill_kids_I_must";
	currentInfraction.Type = Spyglass_InfractionType.Cheating;
	currentInfraction.Date = "05-MAY-22";
	currentInfraction.Reason = "Aimbot.";
	
    infractions.append(clone currentInfraction);
    Spyglass_Infractions["1003374325454"] <- clone infractions;

    // 1011576569232
    infractions = [];
    currentInfraction.ID = 89;
	currentInfraction.PlayerUsername = "DADAG4R";
	currentInfraction.Type = Spyglass_InfractionType.Cheating;
	currentInfraction.Date = "02-MAY-22";
	currentInfraction.Reason = "Aimbot.";
	
    infractions.append(clone currentInfraction);
    Spyglass_Infractions["1011576569232"] <- clone infractions;

    // 2262483997
    infractions = [];
    currentInfraction.ID = 90;
	currentInfraction.PlayerUsername = "SilentSnice";
	currentInfraction.Type = Spyglass_InfractionType.Cheating;
	currentInfraction.Date = "02-MAY-22";
	currentInfraction.Reason = "Emit, invincibility, speedhacks.";
	
    infractions.append(clone currentInfraction);
    Spyglass_Infractions["2262483997"] <- clone infractions;

    // 1007712991451
    infractions = [];
    currentInfraction.ID = 102;
	currentInfraction.PlayerUsername = "VenoPadro";
	currentInfraction.Type = Spyglass_InfractionType.Discrimination;
	currentInfraction.Date = "05-APR-22";
	currentInfraction.Reason = "Racial slur and telling a player to commit suicide.";
	
    infractions.append(clone currentInfraction);
    currentInfraction.ID = 101;
	currentInfraction.PlayerUsername = "VenoPadro";
	currentInfraction.Type = Spyglass_InfractionType.Discrimination;
	currentInfraction.Date = "07-APR-22";
	currentInfraction.Reason = "Every listable discrimination offence.";
	
    infractions.append(clone currentInfraction);
    currentInfraction.ID = 91;
	currentInfraction.PlayerUsername = "VenoPadro";
	currentInfraction.Type = Spyglass_InfractionType.Discrimination;
	currentInfraction.Date = "01-MAY-22";
	currentInfraction.Reason = "Racial slurs in chat.";
	
    infractions.append(clone currentInfraction);
    Spyglass_Infractions["1007712991451"] <- clone infractions;

    // 1008868194618
    infractions = [];
    currentInfraction.ID = 93;
	currentInfraction.PlayerUsername = "MrHuggy";
	currentInfraction.Type = Spyglass_InfractionType.Cheating;
	currentInfraction.Date = "24-APR-22";
	currentInfraction.Reason = "Aimbot.";
	
    infractions.append(clone currentInfraction);
    Spyglass_Infractions["1008868194618"] <- clone infractions;

    // 1006345795805
    infractions = [];
    currentInfraction.ID = 95;
	currentInfraction.PlayerUsername = "cheesester2010";
	currentInfraction.Type = Spyglass_InfractionType.Toxicity;
	currentInfraction.Date = "23-APR-22";
	currentInfraction.Reason = "Spamming nazi glorification.";
	
    infractions.append(clone currentInfraction);
    Spyglass_Infractions["1006345795805"] <- clone infractions;

    // 1010187802107
    infractions = [];
    currentInfraction.ID = 96;
	currentInfraction.PlayerUsername = "FakyCockCheese";
	currentInfraction.Type = Spyglass_InfractionType.Spamming;
	currentInfraction.Date = "18-APR-22";
	currentInfraction.Reason = "Chat spam.";
	
    infractions.append(clone currentInfraction);
    Spyglass_Infractions["1010187802107"] <- clone infractions;

    // 1011202965727
    infractions = [];
    currentInfraction.ID = 97;
	currentInfraction.PlayerUsername = "BeetusTheJanitor";
	currentInfraction.Type = Spyglass_InfractionType.Spamming;
	currentInfraction.Date = "12-APR-22";
	currentInfraction.Reason = "Spamming (using patched connect exploit).";
	
    infractions.append(clone currentInfraction);
    Spyglass_Infractions["1011202965727"] <- clone infractions;

    // 1013525112146
    infractions = [];
    currentInfraction.ID = 98;
	currentInfraction.PlayerUsername = "CakesCockCheese";
	currentInfraction.Type = Spyglass_InfractionType.Toxicity;
	currentInfraction.Date = "10-APR-22";
	currentInfraction.Reason = "Spamming insults in chat.";
	
    infractions.append(clone currentInfraction);
    currentInfraction.ID = 99;
	currentInfraction.PlayerUsername = "CakessCumSock";
	currentInfraction.Type = Spyglass_InfractionType.Spamming;
	currentInfraction.Date = "10-APR-22";
	currentInfraction.Reason = "Spamming chat.";
	
    infractions.append(clone currentInfraction);
    Spyglass_Infractions["1013525112146"] <- clone infractions;

    // 2848731946
    infractions = [];
    currentInfraction.ID = 100;
	currentInfraction.PlayerUsername = "Raleighl";
	currentInfraction.Type = Spyglass_InfractionType.Discrimination;
	currentInfraction.Date = "10-APR-22";
	currentInfraction.Reason = "Racial slur in chat.";
	
    infractions.append(clone currentInfraction);
    Spyglass_Infractions["2848731946"] <- clone infractions;

    // 1007473846648
    infractions = [];
    currentInfraction.ID = 103;
	currentInfraction.PlayerUsername = "deXSQL";
	currentInfraction.Type = Spyglass_InfractionType.Cheating;
	currentInfraction.Date = "04-APR-22";
	currentInfraction.Reason = "Aimbot.";
	
    infractions.append(clone currentInfraction);
    Spyglass_Infractions["1007473846648"] <- clone infractions;

    // 1001190508849
    infractions = [];
    currentInfraction.ID = 105;
	currentInfraction.PlayerUsername = "WorldOfShanks";
	currentInfraction.Type = Spyglass_InfractionType.Discrimination;
	currentInfraction.Date = "30-MAR-22";
	currentInfraction.Reason = "Racial slurs in chat.";
	
    infractions.append(clone currentInfraction);
    Spyglass_Infractions["1001190508849"] <- clone infractions;

    // 1007311496164
    infractions = [];
    currentInfraction.ID = 107;
	currentInfraction.PlayerUsername = "BunnyhopEnjoyer";
	currentInfraction.Type = Spyglass_InfractionType.Discrimination;
	currentInfraction.Date = "17-MAR-22";
	currentInfraction.Reason = "Racial slurs in chat.";
	
    infractions.append(clone currentInfraction);
    currentInfraction.ID = 106;
	currentInfraction.PlayerUsername = "BunnyhopEnjoyer";
	currentInfraction.Type = Spyglass_InfractionType.Discrimination;
	currentInfraction.Date = "17-MAR-22";
	currentInfraction.Reason = "Racial slur in chat.";
	
    infractions.append(clone currentInfraction);
    Spyglass_Infractions["1007311496164"] <- clone infractions;

    // 1007254462376
    infractions = [];
    currentInfraction.ID = 108;
	currentInfraction.PlayerUsername = "RespawnEntertainment";
	currentInfraction.Type = Spyglass_InfractionType.Cheating;
	currentInfraction.Date = "13-MAR-22";
	currentInfraction.Reason = "Instant respawn exploit.";
	
    infractions.append(clone currentInfraction);
    Spyglass_Infractions["1007254462376"] <- clone infractions;

    // 1000122980241
    infractions = [];
    currentInfraction.ID = 109;
	currentInfraction.PlayerUsername = "Naicrez";
	currentInfraction.Type = Spyglass_InfractionType.Discrimination;
	currentInfraction.Date = "10-MAR-22";
	currentInfraction.Reason = "Racial slurs in chat.";
	
    infractions.append(clone currentInfraction);
    Spyglass_Infractions["1000122980241"] <- clone infractions;

    // 1012628317658
    infractions = [];
    currentInfraction.ID = 110;
	currentInfraction.PlayerUsername = "WellWhelve";
	currentInfraction.Type = Spyglass_InfractionType.Cheating;
	currentInfraction.Date = "10-MAR-22";
	currentInfraction.Reason = "Wallhacks, soft aimbot.";
	
    infractions.append(clone currentInfraction);
    Spyglass_Infractions["1012628317658"] <- clone infractions;

    // 1003233974297
    infractions = [];
    currentInfraction.ID = 131;
	currentInfraction.PlayerUsername = "MeowSolo";
	currentInfraction.Type = Spyglass_InfractionType.Cheating;
	currentInfraction.Date = "11-FEB-22";
	currentInfraction.Reason = "Aimbot and misc exploits.";
	
    infractions.append(clone currentInfraction);
    currentInfraction.ID = 113;
	currentInfraction.PlayerUsername = "PureRupted";
	currentInfraction.Type = Spyglass_InfractionType.Spoof;
	currentInfraction.Date = "06-MAR-22";
	currentInfraction.Reason = "(Spoofed) Aimbot and invincibility.";
	
    infractions.append(clone currentInfraction);
    currentInfraction.ID = 112;
	currentInfraction.PlayerUsername = "fart_eater";
	currentInfraction.Type = Spyglass_InfractionType.Cheating;
	currentInfraction.Date = "06-MAR-22";
	currentInfraction.Reason = "Aimbot, wallhacks.";
	
    infractions.append(clone currentInfraction);
    currentInfraction.ID = 111;
	currentInfraction.PlayerUsername = "unconnected";
	currentInfraction.Type = Spyglass_InfractionType.Cheating;
	currentInfraction.Date = "08-MAR-22";
	currentInfraction.Reason = "Noclip, aimbot, speedhacks.";
	
    infractions.append(clone currentInfraction);
    Spyglass_Infractions["1003233974297"] <- clone infractions;

    // 1000046162248
    infractions = [];
    currentInfraction.ID = 115;
	currentInfraction.PlayerUsername = "CoolFerCats";
	currentInfraction.Type = Spyglass_InfractionType.Cheating;
	currentInfraction.Date = "27-FEB-22";
	currentInfraction.Reason = "Aimbot and wallhacks.";
	
    infractions.append(clone currentInfraction);
    Spyglass_Infractions["1000046162248"] <- clone infractions;

    // 1005934084362
    infractions = [];
    currentInfraction.ID = 116;
	currentInfraction.PlayerUsername = "jiji73";
	currentInfraction.Type = Spyglass_InfractionType.Cheating;
	currentInfraction.Date = "24-FEB-22";
	currentInfraction.Reason = "Aimbot.";
	
    infractions.append(clone currentInfraction);
    Spyglass_Infractions["1005934084362"] <- clone infractions;

    // 1008860702285
    infractions = [];
    currentInfraction.ID = 120;
	currentInfraction.PlayerUsername = "swift_owl808yt";
	currentInfraction.Type = Spyglass_InfractionType.Cheating;
	currentInfraction.Date = "18-FEB-22";
	currentInfraction.Reason = "Aimbot.";
	
    infractions.append(clone currentInfraction);
    currentInfraction.ID = 119;
	currentInfraction.PlayerUsername = "swift_owl808yt";
	currentInfraction.Type = Spyglass_InfractionType.Cheating;
	currentInfraction.Date = "19-FEB-22";
	currentInfraction.Reason = "Aimbot.";
	
    infractions.append(clone currentInfraction);
    currentInfraction.ID = 117;
	currentInfraction.PlayerUsername = "swift_owl808yt";
	currentInfraction.Type = Spyglass_InfractionType.Cheating;
	currentInfraction.Date = "23-FEB-22";
	currentInfraction.Reason = "Aimbot and wallhacks.";
	
    infractions.append(clone currentInfraction);
    Spyglass_Infractions["1008860702285"] <- clone infractions;

    // 1006954720415
    infractions = [];
    currentInfraction.ID = 118;
	currentInfraction.PlayerUsername = "Ace_PandaEyes23";
	currentInfraction.Type = Spyglass_InfractionType.Cheating;
	currentInfraction.Date = "19-FEB-22";
	currentInfraction.Reason = "Aimbot.";
	
    infractions.append(clone currentInfraction);
    Spyglass_Infractions["1006954720415"] <- clone infractions;

    // 1001463354043
    infractions = [];
    currentInfraction.ID = 121;
	currentInfraction.PlayerUsername = "DezSquad";
	currentInfraction.Type = Spyglass_InfractionType.Cheating;
	currentInfraction.Date = "18-FEB-22";
	currentInfraction.Reason = "Aimbot and wallhacks.";
	
    infractions.append(clone currentInfraction);
    Spyglass_Infractions["1001463354043"] <- clone infractions;

    // 1011555553975
    infractions = [];
    currentInfraction.ID = 123;
	currentInfraction.PlayerUsername = "dalkryesaaa";
	currentInfraction.Type = Spyglass_InfractionType.Cheating;
	currentInfraction.Date = "17-FEB-22";
	currentInfraction.Reason = "Aimbot.";
	
    infractions.append(clone currentInfraction);
    Spyglass_Infractions["1011555553975"] <- clone infractions;

    // 1003695138110
    infractions = [];
    currentInfraction.ID = 124;
	currentInfraction.PlayerUsername = "benjibenji21";
	currentInfraction.Type = Spyglass_InfractionType.Cheating;
	currentInfraction.Date = "16-FEB-22";
	currentInfraction.Reason = "Aimbot.";
	
    infractions.append(clone currentInfraction);
    Spyglass_Infractions["1003695138110"] <- clone infractions;

    // 1006346760265
    infractions = [];
    currentInfraction.ID = 125;
	currentInfraction.PlayerUsername = "xenobility";
	currentInfraction.Type = Spyglass_InfractionType.Cheating;
	currentInfraction.Date = "06-FEB-22";
	currentInfraction.Reason = "Aimbot.";
	
    infractions.append(clone currentInfraction);
    Spyglass_Infractions["1006346760265"] <- clone infractions;

    // 1010725680144
    infractions = [];
    currentInfraction.ID = 128;
	currentInfraction.PlayerUsername = "Razzy1234";
	currentInfraction.Type = Spyglass_InfractionType.Cheating;
	currentInfraction.Date = "16-FEB-22";
	currentInfraction.Reason = "Aimbot and wallhacks.";
	
    infractions.append(clone currentInfraction);
    currentInfraction.ID = 126;
	currentInfraction.PlayerUsername = "Razzy1234";
	currentInfraction.Type = Spyglass_InfractionType.Cheating;
	currentInfraction.Date = "16-FEB-22";
	currentInfraction.Reason = "Aimbot and wallhacks.";
	
    infractions.append(clone currentInfraction);
    Spyglass_Infractions["1010725680144"] <- clone infractions;

    // 2272897911
    infractions = [];
    currentInfraction.ID = 127;
	currentInfraction.PlayerUsername = "t0asts";
	currentInfraction.Type = Spyglass_InfractionType.Cheating;
	currentInfraction.Date = "09-FEB-22";
	currentInfraction.Reason = "Aimbot and wallhacks.";
	
    infractions.append(clone currentInfraction);
    Spyglass_Infractions["2272897911"] <- clone infractions;

    // 1006923229024
    infractions = [];
    currentInfraction.ID = 129;
	currentInfraction.PlayerUsername = "PlatiniumDong";
	currentInfraction.Type = Spyglass_InfractionType.Cheating;
	currentInfraction.Date = "09-FEB-22";
	currentInfraction.Reason = "Aimbot and wallhacks.";
	
    infractions.append(clone currentInfraction);
    Spyglass_Infractions["1006923229024"] <- clone infractions;

    // 1012583183520
    infractions = [];
    currentInfraction.ID = 130;
	currentInfraction.PlayerUsername = "ezyon_darknessss";
	currentInfraction.Type = Spyglass_InfractionType.Cheating;
	currentInfraction.Date = "11-FEB-22";
	currentInfraction.Reason = "Aimbot.";
	
    infractions.append(clone currentInfraction);
    Spyglass_Infractions["1012583183520"] <- clone infractions;

    // 2250487322
    infractions = [];
    currentInfraction.ID = 132;
	currentInfraction.PlayerUsername = "refractxvi";
	currentInfraction.Type = Spyglass_InfractionType.Discrimination;
	currentInfraction.Date = "30-APR-22";
	currentInfraction.Reason = "Racial slurs in chat.";
	
    infractions.append(clone currentInfraction);
    Spyglass_Infractions["2250487322"] <- clone infractions;

    // 2839761312
    infractions = [];
    currentInfraction.ID = 134;
	currentInfraction.PlayerUsername = "FrAkIngPIlOtfAll";
	currentInfraction.Type = Spyglass_InfractionType.Discrimination;
	currentInfraction.Date = "10-APR-22";
	currentInfraction.Reason = "Racial slur in chat.";
	
    infractions.append(clone currentInfraction);
    currentInfraction.ID = 133;
	currentInfraction.PlayerUsername = "FrAkIngPIlOtfAll";
	currentInfraction.Type = Spyglass_InfractionType.Toxicity;
	currentInfraction.Date = "01-MAY-22";
	currentInfraction.Reason = "Telling players to commit suicide.";
	
    infractions.append(clone currentInfraction);
    Spyglass_Infractions["2839761312"] <- clone infractions;

    // 1008441324399
    infractions = [];
    currentInfraction.ID = 135;
	currentInfraction.PlayerUsername = "The-0v3rki113r";
	currentInfraction.Type = Spyglass_InfractionType.Discrimination;
	currentInfraction.Date = "04-JUN-22";
	currentInfraction.Reason = "Racism and antisemitism.";
	
    infractions.append(clone currentInfraction);
    Spyglass_Infractions["1008441324399"] <- clone infractions;

    // 1002319733641
    infractions = [];
    currentInfraction.ID = 136;
	currentInfraction.PlayerUsername = "fenderbg97";
	currentInfraction.Type = Spyglass_InfractionType.Discrimination;
	currentInfraction.Date = "18-AUG-22";
	currentInfraction.Reason = "Racial slur in chat.";
	
    infractions.append(clone currentInfraction);
    Spyglass_Infractions["1002319733641"] <- clone infractions;

    // 1007028668642
    infractions = [];
    currentInfraction.ID = 137;
	currentInfraction.PlayerUsername = "_R34lityCh3ck_";
	currentInfraction.Type = Spyglass_InfractionType.Spoof;
	currentInfraction.Date = "02-JUL-22";
	currentInfraction.Reason = "(Spoofed) Aimbot and wallhacks.";
	
    infractions.append(clone currentInfraction);
    Spyglass_Infractions["1007028668642"] <- clone infractions;

    // 1013453793571
    infractions = [];
    currentInfraction.ID = 140;
	currentInfraction.PlayerUsername = "zabossthebigboss";
	currentInfraction.Type = Spyglass_InfractionType.Discrimination;
	currentInfraction.Date = "09-JUL-22";
	currentInfraction.Reason = "Racism, transphobia.";
	
    infractions.append(clone currentInfraction);
    currentInfraction.ID = 138;
	currentInfraction.PlayerUsername = "zabossthebigboss";
	currentInfraction.Type = Spyglass_InfractionType.Discrimination;
	currentInfraction.Date = "17-JUL-22";
	currentInfraction.Reason = "Racial and homophobic slurs.";
	
    infractions.append(clone currentInfraction);
    Spyglass_Infractions["1013453793571"] <- clone infractions;

    // 2294597892
    infractions = [];
    currentInfraction.ID = 139;
	currentInfraction.PlayerUsername = "DuckDuckDonkey";
	currentInfraction.Type = Spyglass_InfractionType.Discrimination;
	currentInfraction.Date = "16-JUL-22";
	currentInfraction.Reason = "Racial and homophobic slurs in chat.";
	
    infractions.append(clone currentInfraction);
    Spyglass_Infractions["2294597892"] <- clone infractions;

    // 1003641394598
    infractions = [];
    currentInfraction.ID = 141;
	currentInfraction.PlayerUsername = "FierfekTheKiller";
	currentInfraction.Type = Spyglass_InfractionType.Discrimination;
	currentInfraction.Date = "22-SEPT-22";
	currentInfraction.Reason = "Homophobic slur in chat.";
	
    infractions.append(clone currentInfraction);
    Spyglass_Infractions["1003641394598"] <- clone infractions;

    // 1003285500181
    infractions = [];
    currentInfraction.ID = 142;
	currentInfraction.PlayerUsername = "111mayhem";
	currentInfraction.Type = Spyglass_InfractionType.Discrimination;
	currentInfraction.Date = "26-SEPT-22";
	currentInfraction.Reason = "Racial slur in chat.";
	
    infractions.append(clone currentInfraction);
    Spyglass_Infractions["1003285500181"] <- clone infractions;


    printt("==========================================");
    printt("[Spyglass] Mapping player names to UIDs.  ");
    printt("==========================================");

    Spyglass_PlayerNameUIDMap["lonelykilla23"] <- "1005782992766";
    Spyglass_PlayerNameUIDMap["p4tr1x_g"] <- "1003520719357";
    Spyglass_PlayerNameUIDMap["quadrupeldamag"] <- "1008622084773";
    Spyglass_PlayerNameUIDMap["iamdavidoff2k2"] <- "1011452735139";
    Spyglass_PlayerNameUIDMap["jesusmango"] <- "2655753508";
    Spyglass_PlayerNameUIDMap["medicalmeccanica"] <- "1012893329720";
    Spyglass_PlayerNameUIDMap["kubatdc"] <- "1006249545593";
    Spyglass_PlayerNameUIDMap["wagwanbigmans"] <- "1013244775476";
    Spyglass_PlayerNameUIDMap["mrfogg"] <- "1011345449670";
    Spyglass_PlayerNameUIDMap["concernedpencil0"] <- "1011457670714";
    Spyglass_PlayerNameUIDMap["woahdev"] <- "1007544128057";
    Spyglass_PlayerNameUIDMap["killer69y"] <- "1007319692607";
    Spyglass_PlayerNameUIDMap["xsnipezx21"] <- "1000180140014";
    Spyglass_PlayerNameUIDMap["senpaivt"] <- "1010161190670";
    Spyglass_PlayerNameUIDMap["isnipsnipsnip"] <- "1008988079827";
    Spyglass_PlayerNameUIDMap["uwuhun3ter"] <- "1008122720592";
    Spyglass_PlayerNameUIDMap["battleritepump"] <- "1012632396446";
    Spyglass_PlayerNameUIDMap["ghostxvii"] <- "1000092519211";
    Spyglass_PlayerNameUIDMap["phantom_raimando"] <- "1008973146907";
    Spyglass_PlayerNameUIDMap["coconuts_004"] <- "1011795366781";
    Spyglass_PlayerNameUIDMap["m0rbidc0rvid"] <- "1011134487508";
    Spyglass_PlayerNameUIDMap["g0fesh"] <- "1000186323332";
    Spyglass_PlayerNameUIDMap["awesomeguy41"] <- "1011897054369";
    Spyglass_PlayerNameUIDMap["cheesegratermanx"] <- "1011897054369";
    Spyglass_PlayerNameUIDMap["fuzzqminotaur97"] <- "1009821473677";
    Spyglass_PlayerNameUIDMap["tamagicznaflet"] <- "1011116972357";
    Spyglass_PlayerNameUIDMap["ogtsilva"] <- "2251932307";
    Spyglass_PlayerNameUIDMap["roguebananabtw"] <- "1006063431799";
    Spyglass_PlayerNameUIDMap["floridabiker"] <- "2250141414";
    Spyglass_PlayerNameUIDMap["stefanthegrate16"] <- "1009805930043";
    Spyglass_PlayerNameUIDMap["sumboro"] <- "1008231879388";
    Spyglass_PlayerNameUIDMap["trouble439"] <- "1009767928840";
    Spyglass_PlayerNameUIDMap["mr_notsuspicious"] <- "1004184060749";
    Spyglass_PlayerNameUIDMap["submensch"] <- "1008593965434";
    Spyglass_PlayerNameUIDMap["hextechman"] <- "1013391767921";
    Spyglass_PlayerNameUIDMap["cosmos-da-cat"] <- "1008873731189";
    Spyglass_PlayerNameUIDMap["thewarflash"] <- "2321091843";
    Spyglass_PlayerNameUIDMap["thavage_soul"] <- "1009690917669";
    Spyglass_PlayerNameUIDMap["yourtrashkid1215"] <- "1000349712299";
    Spyglass_PlayerNameUIDMap["sammiedonk"] <- "1007299698120";
    Spyglass_PlayerNameUIDMap["nicklink217"] <- "1010773614705";
    Spyglass_PlayerNameUIDMap["superblyatman101"] <- "1009589129089";
    Spyglass_PlayerNameUIDMap["xxh1ghrollerxx"] <- "1009417714028";
    Spyglass_PlayerNameUIDMap["therealepicflame"] <- "1006636445131";
    Spyglass_PlayerNameUIDMap["definitionofcool"] <- "1007313236586";
    Spyglass_PlayerNameUIDMap["eyeballmuncher47"] <- "1007313236586";
    Spyglass_PlayerNameUIDMap["chargehack"] <- "1011158646016";
    Spyglass_PlayerNameUIDMap["fdac3c83ccbd903fa5c1499a6f6cad24"] <- "2311733905";
    Spyglass_PlayerNameUIDMap["cabober"] <- "1011604298047";
    Spyglass_PlayerNameUIDMap["newew"] <- "1009796277318";
    Spyglass_PlayerNameUIDMap["shadow443"] <- "1009685493971";
    Spyglass_PlayerNameUIDMap["supal33thacker"] <- "1008227051828";
    Spyglass_PlayerNameUIDMap["exact_value"] <- "1007901881439";
    Spyglass_PlayerNameUIDMap["thatfella_27_"] <- "1006358680073";
    Spyglass_PlayerNameUIDMap["dester441"] <- "1010517024687";
    Spyglass_PlayerNameUIDMap["moxi76"] <- "1012276100023";
    Spyglass_PlayerNameUIDMap["watzkrakenn"] <- "1008904554095";
    Spyglass_PlayerNameUIDMap["ohmangoh"] <- "1013163567703";
    Spyglass_PlayerNameUIDMap["xirunzxboxlive_"] <- "1011777372037";
    Spyglass_PlayerNameUIDMap["whotfiswanderer"] <- "1011777372037";
    Spyglass_PlayerNameUIDMap["evilsparky420"] <- "2342589311";
    Spyglass_PlayerNameUIDMap["peigengchen"] <- "1012599329074";
    Spyglass_PlayerNameUIDMap["kill_kids_i_must"] <- "1003374325454";
    Spyglass_PlayerNameUIDMap["dadag4r"] <- "1011576569232";
    Spyglass_PlayerNameUIDMap["silentsnice"] <- "2262483997";
    Spyglass_PlayerNameUIDMap["venopadro"] <- "1007712991451";
    Spyglass_PlayerNameUIDMap["mrhuggy"] <- "1008868194618";
    Spyglass_PlayerNameUIDMap["cheesester2010"] <- "1006345795805";
    Spyglass_PlayerNameUIDMap["fakycockcheese"] <- "1010187802107";
    Spyglass_PlayerNameUIDMap["beetusthejanitor"] <- "1011202965727";
    Spyglass_PlayerNameUIDMap["cakescockcheese"] <- "1013525112146";
    Spyglass_PlayerNameUIDMap["cakesscumsock"] <- "1013525112146";
    Spyglass_PlayerNameUIDMap["raleighl"] <- "2848731946";
    Spyglass_PlayerNameUIDMap["dexsql"] <- "1007473846648";
    Spyglass_PlayerNameUIDMap["worldofshanks"] <- "1001190508849";
    Spyglass_PlayerNameUIDMap["bunnyhopenjoyer"] <- "1007311496164";
    Spyglass_PlayerNameUIDMap["respawnentertainment"] <- "1007254462376";
    Spyglass_PlayerNameUIDMap["naicrez"] <- "1000122980241";
    Spyglass_PlayerNameUIDMap["wellwhelve"] <- "1012628317658";
    Spyglass_PlayerNameUIDMap["unconnected"] <- "1003233974297";
    Spyglass_PlayerNameUIDMap["fart_eater"] <- "1003233974297";
    Spyglass_PlayerNameUIDMap["purerupted"] <- "1003233974297";
    Spyglass_PlayerNameUIDMap["meowsolo"] <- "1003233974297";
    Spyglass_PlayerNameUIDMap["coolfercats"] <- "1000046162248";
    Spyglass_PlayerNameUIDMap["jiji73"] <- "1005934084362";
    Spyglass_PlayerNameUIDMap["swift_owl808yt"] <- "1008860702285";
    Spyglass_PlayerNameUIDMap["ace_pandaeyes23"] <- "1006954720415";
    Spyglass_PlayerNameUIDMap["dezsquad"] <- "1001463354043";
    Spyglass_PlayerNameUIDMap["dalkryesaaa"] <- "1011555553975";
    Spyglass_PlayerNameUIDMap["benjibenji21"] <- "1003695138110";
    Spyglass_PlayerNameUIDMap["xenobility"] <- "1006346760265";
    Spyglass_PlayerNameUIDMap["razzy1234"] <- "1010725680144";
    Spyglass_PlayerNameUIDMap["t0asts"] <- "2272897911";
    Spyglass_PlayerNameUIDMap["platiniumdong"] <- "1006923229024";
    Spyglass_PlayerNameUIDMap["ezyon_darknessss"] <- "1012583183520";
    Spyglass_PlayerNameUIDMap["refractxvi"] <- "2250487322";
    Spyglass_PlayerNameUIDMap["frakingpilotfall"] <- "2839761312";
    Spyglass_PlayerNameUIDMap["the-0v3rki113r"] <- "1008441324399";
    Spyglass_PlayerNameUIDMap["fenderbg97"] <- "1002319733641";
    Spyglass_PlayerNameUIDMap["_r34litych3ck_"] <- "1007028668642";
    Spyglass_PlayerNameUIDMap["zabossthebigboss"] <- "1013453793571";
    Spyglass_PlayerNameUIDMap["duckduckdonkey"] <- "2294597892";
    Spyglass_PlayerNameUIDMap["fierfekthekiller"] <- "1003641394598";
    Spyglass_PlayerNameUIDMap["111mayhem"] <- "1003285500181";

    printt("==========================================");
    printt("[Spyglass] Loaded player database.        ");
    printt("==========================================");
}
